---
title: 'DDS: Case Study 2'
author: "Jordan Eaddy"
date: "12/7/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r Packages and Data}
library(tidyverse)
library(GGally)
library(inspectdf)
library(scales)
library(class)
library(caret)
library(e1071)
library(readxl)
library(Metrics)
library(ggthemes)
library(DT)


CSD <- read_csv("~/Desktop/Final Project Data/CaseStudy2-data.csv")
Salary <- read_excel("~/Desktop/Final Project Data/CaseStudy2CompSet No Salary.xlsx")




```


```{r Pre-Eda}

sapply(CSD,function(x)sum(is.na(x))) # No missing Vars

# Data Mutating
CSD$Attrition<-ifelse(CSD$Attrition=="Yes",1,0) # Converted Attrition to a logical operation. 1 = Yes, 0 = No
CSD$OverTime<-ifelse(CSD$OverTime=="No",0,1) # Converted Overtime to a logical operation, 1 = Yes, 0 = NO

CSD %>% inspect_cor()
#I want to narrow in on just how attrition looks with each variable
modelcsd %>% inspect_cor(with_col = "Attrition")
#Visualization of above
CSD %>% inspect_cor() %>% 
  show_plot()



```


```{r Insight: Attrition}
CSD %>% 
  group_by(Attrition) %>% 
  summarise(Attrition_Percent= 100 * n()/ nrow(CSD))
# ** Only 16 % of our data actually left their position for one reason or another**
# Note to self: This may cause problems in the modeling phase. Consider sampling ideas. 









```

```{r FINAL Insight: Job Role Trends}
# Now I want to know what our population looks like by job role

CSD %>%  # Viz
  ggplot(aes(JobRole, fill = JobRole))+
  geom_bar(aes(y=(..count..)/sum(..count..)))+
  theme(legend.position = "None")+
  scale_y_continuous(labels= percent)+
    labs(title= "Job Role Percentages", y = "Percentage", x = "Job Role",tag = "Fig. 1" )+
  theme_igray()

# Income by Job Title Distributions 
CSD %>% 
  ggplot(aes(reorder(x=JobRole,-MonthlyIncome),y=MonthlyIncome, fill= JobRole))+
  geom_boxplot()+
  scale_y_continuous(labels= dollar_format())+
  labs(title= "Income by Role", y = "Income", x = "Job Title", tag = "Fig. 3")+
  theme_economist_white()+
  theme(legend.position = "none",axis.title.y = element_text(vjust= 4) )+
  guides(x = guide_axis(n.dodge= 2))

# 16 Percent left thier role
CSD %>% 
  group_by(Attrition) %>% 
  summarise(Attrition_Percent= 100 * n()/ nrow(CSD))

# Attrition by Job Role
CSD %>% 
  ggplot(aes(JobRole, y=(..count..)/sum(..count..), fill=Attrition))+
  geom_bar()+
  theme_economist_white()+
  theme(axis.title.x = element_text(vjust=-4))+
  labs(title= "Attrition By Job Role", x = "Job Role", y= "", tag= "Fig. 2")+
  scale_y_continuous(labels = percent)
         # Sales Reps have high attrition, despite having a Job Satisfaction rating in the upper percentile of our data. Monthly Income

  
CSD %>%
  ggplot(aes(JobInvolvement, fill=Attrition))+
  geom_bar()


```

```{r}
CSD %>%  # Table
  group_by(JobRole) %>% 
  summarise(percent= 100 * n()/ nrow(CSD))

# Lab Tech(17), Manufacturing Director(10), Research Scientist(19),Sales Exec(22), account for the vast majority of our data.


# Of the Job Titles, which ones have the lowest job satisfaction

CSD %>% 
  ggplot(aes(JobSatisfaction, JobRole, fill = factor(Attrition)))+
  geom_bar(stat= "identity")


# Income by Job Title Distributions 
CSD %>% 
  ggplot(aes(reorder(x=JobRole,-MonthlyIncome),y=MonthlyIncome))+
  geom_boxplot()+
  scale_y_continuous(labels= dollar_format())+
  labs(title= "Income by Role", y = "Income", x = "Job Title", tag = "Fig. 2")


# Income by Education Distribution

CSD %>% 
  ggplot(aes(reorder(Education, - MonthlyIncome), MonthlyIncome, fill = ))+
  geom_boxplot()+
  scale_y_continuous(labels= dollar_format())+
  theme_wsj()



```


```{r Job Level}
CSD %>% 
  ggplot(aes(reorder(JobLevel, - MonthlyIncome), MonthlyIncome))+
  geom_boxplot()
# As expected, Job levels by Monthly Income have a strong linear relationship





```





```{r Gender Insights}
CSD %>%  # Table
  group_by(Gender) %>% 
  summarise(percent= 100 * n()/ nrow(CSD))
# Our Data is 40 % F and 59 % M

CSD %>% 
  ggplot(aes(Gender, MonthlyIncome))+
  geom_boxplot()
# Men and Woman are paid fairly evenly



```


```{r}
JobLevel,TotalWorkingYears, MonthlyIncome, Age, JobRole




```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

